name: PrimeiroPlugin
version: 2.3-SNAPSHOT
main: br.com.mxtheuz.TutorialPlugin

commands:
  dono:
  admin:
  moderador:
  discord:
  perm:
  unperm:
  kit:
  vip:
  unvip:

permissions:
  admin:
    description: Administradores do nosso servidor
  moderador:
    description: Moderadores do nosso servidor


